cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('clear/', views.clear_cart, name='clear_cart'),
]

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook

app_name = 'checkout'

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('checkout_success/<str:order_number>', views.checkout_success, name='checkout_success'),
    path('cache_checkout_data/', views.cache_checkout_data, name='cache_checkout_data'),
    path('wh/', webhook, name='webhook'),
]

glossy/urls.py
"""
URL configuration for glossy project.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('', include('pages.urls')),  # Changed to pages.urls for home page
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom error handlers
handler404 = 'glossy.views.handler404'
handler500 = 'glossy.views.handler500'
handler403 = 'glossy.views.handler403'

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('category/<str:category_name>/', views.product_category, name='product_category'),
    path('skincare/', views.skincare, name='skincare'),
    path('makeup/', views.makeup, name='makeup'),
    path('body-hair/', views.body_hair, name='body_hair'),
    path('special-offers/', views.special_offers, name='special_offers'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from products.models import Product, ProductVariant

def view_cart(request):
    """A view to render the cart contents page"""
    return render(request, 'cart/cart.html')


def add_to_cart(request, item_id):
    """Add a quantity of the specified product to the shopping cart"""
    try:
        product = get_object_or_404(Product, pk=item_id)
        quantity = int(request.POST.get('quantity', 1))
        redirect_url = request.POST.get('redirect_url')
        variant_id = request.POST.get('variant_id')
        cart = request.session.get('cart', {})
        
        if variant_id:
            variant = get_object_or_404(ProductVariant, pk=variant_id)
            item_id_str = f"{item_id}_{variant_id}"
            
            if item_id_str in cart:
                cart[item_id_str] += quantity
                messages.success(request, f'Updated {variant.name} {product.name} quantity to {cart[item_id_str]}')
            else:
                cart[item_id_str] = quantity
                messages.success(request, f'Added {variant.name} {product.name} to your cart')
        else:
            if str(item_id) in cart:
                cart[str(item_id)] += quantity
                messages.success(request, f'Updated {product.name} quantity to {cart[str(item_id)]}')
            else:
                cart[str(item_id)] = quantity
                messages.success(request, f'Added {product.name} to your cart')
        
        request.session['cart'] = cart
        return redirect(redirect_url)
    except Exception as e:
        messages.error(request, f"Error adding item to cart: {e}")
        return redirect(redirect_url)


def adjust_cart(request, item_id):
    """Adjust the quantity of the specified product to the specified amount"""
    try:
        quantity = int(request.POST.get('quantity'))
        cart = request.session.get('cart', {})
        
        # Check if item_id exists in cart
        if item_id in cart:
            if quantity > 0:
                cart[item_id] = quantity
                # Display success message indicating the item was updated
                if '_' in item_id:
                    # It's a product variant
                    product_id, variant_id = item_id.split('_')
                    product = get_object_or_404(Product, pk=product_id)
                    variant = get_object_or_404(ProductVariant, pk=variant_id)
                    messages.success(request, f'Updated {variant.name} {product.name} quantity to {quantity}')
                else:
                    # It's a regular product
                    product = get_object_or_404(Product, pk=item_id)
                    messages.success(request, f'Updated {product.name} quantity to {quantity}')
            else:
                cart.pop(item_id)
                # Display success message indicating the item was removed
                if '_' in item_id:
                    # It's a product variant
                    product_id, variant_id = item_id.split('_')
                    product = get_object_or_404(Product, pk=product_id)
                    variant = get_object_or_404(ProductVariant, pk=variant_id)
                    messages.success(request, f'Removed {variant.name} {product.name} from your cart')
                else:
                    # It's a regular product
                    product = get_object_or_404(Product, pk=item_id)
                    messages.success(request, f'Removed {product.name} from your cart')
        
        request.session['cart'] = cart
        return redirect(reverse('cart:view_cart'))
    except Exception as e:
        messages.error(request, f"Error updating cart: {e}")
        return redirect(reverse('cart:view_cart'))


def remove_from_cart(request, item_id):
    """Remove the item from the shopping cart"""
    try:
        cart = request.session.get('cart', {})
        
        if item_id in cart:
            cart.pop(item_id)
            request.session['cart'] = cart
            return HttpResponse(status=200)
        else:
            return HttpResponse(status=404)
    except Exception as e:
        return HttpResponse(content=str(e), status=500)


def clear_cart(request):
    """Clear all items from the shopping cart"""
    try:
        # Reset the cart to an empty dictionary
        request.session['cart'] = {}
        messages.success(request, 'Your cart has been cleared')
        return redirect(reverse('cart:view_cart'))
    except Exception as e:
        messages.error(request, f"Error clearing cart: {e}")
        return redirect(reverse('cart:view_cart'))

templates/cart/cart.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container mb-2">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4">Shopping Cart</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col">
            {% if cart_items %}
                <div class="table-responsive rounded">
                    <table class="table table-sm table-borderless">
                        <thead class="text-black">
                            <tr>
                                <th scope="col">Product Info</th>
                                <th scope="col"></th>
                                <th scope="col">Price</th>
                                <th scope="col">Qty</th>
                                <th scope="col">Subtotal</th>
                            </tr>
                        </thead>

                        {% for item in cart_items %}
                            <tr>
                                <td class="p-3 w-25">
                                    {% if item.product.image %}
                                    <img class="img-fluid rounded" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
                                    {% else %}
                                    <img class="img-fluid rounded" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
                                    {% endif %}
                                </td>
                                <td class="py-3">
                                    <p class="my-0"><strong>{{ item.product.name }}</strong></p>
                                    {% if item.variant %}
                                    <p class="my-0 small text-muted">Variant: {{ item.variant.name }}</p>
                                    {% endif %}
                                </td>
                                <td class="py-3">
                                    {% if item.variant %}
                                    <p class="my-0">Rs.{{ item.variant.final_price }}</p>
                                    {% else %}
                                    <p class="my-0">Rs.{{ item.product.price }}</p>
                                    {% endif %}
                                </td>
                                <td class="py-3 w-25">
                                    <form class="form update-form" method="POST" action="{% url 'cart:adjust_cart' item.item_id %}">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <button class="decrement-qty btn btn-sm btn-pink rounded-0" 
                                                        data-item_id="{{ item.item_id }}" id="decrement-qty_{{ item.item_id }}">
                                                        <span>
                                                            <i class="fas fa-minus fa-sm"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                                <input class="form-control form-control-sm qty_input" type="number"
                                                    name="quantity" value="{{ item.quantity }}" min="1" max="99"
                                                    data-item_id="{{ item.item_id }}"
                                                    id="id_qty_{{ item.item_id }}">
                                                <div class="input-group-append">
                                                    <button class="increment-qty btn btn-sm btn-pink rounded-0"
                                                        data-item_id="{{ item.item_id }}" id="increment-qty_{{ item.item_id }}">
                                                        <span>
                                                            <i class="fas fa-plus fa-sm"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                    <a class="update-link text-info"><small>Update</small></a>
                                    <a class="remove-item text-danger float-right" id="remove_{{ item.item_id }}"><small>Remove</small></a>
                                </td>
                                <td class="py-3">
                                    <p class="my-0">Rs.{{ item.subtotal }}</p>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="5" class="pt-5 text-right">
                                <h6><strong>Bag Total: Rs.{{ total|floatformat:2 }}</strong></h6>
                                <h6>Delivery: Rs.{{ delivery|floatformat:2 }}</h6>
                                <h4 class="mt-4"><strong>Grand Total: Rs.{{ grand_total|floatformat:2 }}</strong></h4>
                                {% if free_delivery_delta > 0 %}
                                    <p class="mb-1 text-danger">
                                        You could get free delivery by spending just <strong>Rs.{{ free_delivery_delta }}</strong> more!
                                    </p>
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td colspan="5" class="text-right">
                                <a href="{% url 'products:all_products' %}" class="btn btn-outline-black rounded-0 btn-lg">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <a href="{% url 'checkout:checkout' %}" class="btn btn-pink rounded-0 btn-lg">
                                    <span class="text-uppercase">Secure Checkout</span>
                                    <span class="icon">
                                        <i class="fas fa-lock"></i>
                                    </span>
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            {% else %}
                <p class="lead mb-5">Your cart is empty.</p>
                <a href="{% url 'products:all_products' %}" class="btn btn-outline-black rounded-0 btn-lg">
                    <span class="icon">
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase">Continue Shopping</span>
                </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}

<script>
    // Update quantity on click
    $('.update-link').click(function(e) {
        e.preventDefault();
        console.log('Update link clicked');
        var form = $(this).prev('.update-form');
        form.submit();
    });

    // Remove item and reload on click
    $('.remove-item').click(function(e) {
        e.preventDefault();
        console.log('Remove link clicked');
        
        var csrfToken = "{{ csrf_token }}";
        var itemId = $(this).attr('id').split('remove_')[1];
        var url = `/cart/remove/${itemId}/`;
        
        $.ajax({
            url: url,
            type: 'POST',
            data: {
                'csrfmiddlewaretoken': csrfToken,
            },
            success: function() {
                location.reload();
            },
            error: function(xhr, textStatus, errorThrown) {
                console.error("Error removing item:", errorThrown);
                alert("Sorry, there was a problem removing this item. Please try again.");
            }
        });
    });
</script>
{% endblock %}