accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('order_history/<order_number>', views.order_history, name='order_history'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('clear/', views.clear_cart, name='clear_cart'),
]

glossy/urls.py
"""
URL configuration for glossy project.
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('', include('pages.urls')),  # Changed to pages.urls for home page
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom error handlers
handler404 = 'glossy.views.handler404'
handler500 = 'glossy.views.handler500'
handler403 = 'glossy.views.handler403'

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms/', views.terms, name='terms'),
    path('shipping-returns/', views.shipping_returns, name='shipping_returns'),
    path('contact/', views.contact, name='contact'),
    path('contact/submit/', views.contact_submit, name='contact_submit'),
    path('coming-soon/', views.coming_soon, name='coming_soon'),
    path('coming-soon/<str:feature>/', views.coming_soon, name='coming_soon_feature'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('category/<str:category_name>/', views.product_category, name='product_category'),
    path('skincare/', views.skincare, name='skincare'),
    path('makeup/', views.makeup, name='makeup'),
    path('body-hair/', views.body_hair, name='body_hair'),
    path('special-offers/', views.special_offers, name='special_offers'),
]

templates/includes/footer.html
{% load static %}

<footer class="bg-dark text-white pt-5 pb-4">
    <div class="container">
        <div class="row">
            <!-- Shop Links -->
            <div class="col-12 col-md-3 mb-4">
                <h5 class="text-uppercase mb-4">Shop</h5>
                <ul class="list-unstyled">
                    <li class="mb-2"><a href="{% url 'products:product_category' 'face' %}" class="text-white text-decoration-none">Face Makeup</a></li>
                    <li class="mb-2"><a href="{% url 'products:product_category' 'lips' %}" class="text-white text-decoration-none">Lip Products</a></li>
                    <li class="mb-2"><a href="{% url 'products:product_category' 'eyes' %}" class="text-white text-decoration-none">Eye Makeup</a></li>
                    <li class="mb-2"><a href="{% url 'products:product_category' 'cheeks' %}" class="text-white text-decoration-none">Cheek Products</a></li>
                    <li class="mb-2"><a href="{% url 'products:product_category' 'skincare' %}" class="text-white text-decoration-none">Skincare</a></li>
                    <li class="mb-2"><a href="{% url 'products:product_category' 'brushes' %}" class="text-white text-decoration-none">Brushes & Tools</a></li>
                </ul>
            </div>
            
            <!-- Customer Service -->
            <div class="col-12 col-md-3 mb-4">
                <h5 class="text-uppercase mb-4">Customer Service</h5>
                <ul class="list-unstyled">
                    <li class="mb-2"><a href="{% url 'pages:contact' %}" class="text-white text-decoration-none">Contact Us</a></li>
                    <li class="mb-2"><a href="{% url 'pages:shipping_returns' %}" class="text-white text-decoration-none">Shipping & Returns</a></li>
                    <li class="mb-2"><a href="#" class="text-white text-decoration-none">FAQ</a></li>
                    <li class="mb-2"><a href="#" class="text-white text-decoration-none">Track Your Order</a></li>
                </ul>
            </div>
            
            <!-- Company Info -->
            <div class="col-12 col-md-3 mb-4">
                <h5 class="text-uppercase mb-4">Company</h5>
                <ul class="list-unstyled">
                    <li class="mb-2"><a href="{% url 'pages:about' %}" class="text-white text-decoration-none">About Us</a></li>
                    <li class="mb-2"><a href="#" class="text-white text-decoration-none">Careers</a></li>
                    <li class="mb-2"><a href="{% url 'pages:privacy_policy' %}" class="text-white text-decoration-none">Privacy Policy</a></li>
                    <li class="mb-2"><a href="{% url 'pages:terms' %}" class="text-white text-decoration-none">Terms & Conditions</a></li>
                </ul>
            </div>
            
            <!-- Newsletter and Social -->
            <div class="col-12 col-md-3 mb-4">
                <h5 class="text-uppercase mb-4">Stay Connected</h5>
                <p>Subscribe to our newsletter for exclusive offers and beauty tips.</p>
                <form class="mb-4">
                    <div class="input-group">
                        <input type="email" class="form-control" placeholder="Your email" aria-label="Your email" aria-describedby="subscribe-btn">
                        <div class="input-group-append">
                            <button class="btn btn-pink rounded-0" type="button" id="subscribe-btn">Subscribe</button>
                        </div>
                    </div>
                </form>
                <div class="social-links d-flex">
                    <a href="#" class="text-white me-3 mr-3"><i class="fab fa-facebook-f fa-lg"></i></a>
                    <a href="#" class="text-white me-3 mr-3"><i class="fab fa-twitter fa-lg"></i></a>
                    <a href="#" class="text-white me-3 mr-3"><i class="fab fa-instagram fa-lg"></i></a>
                    <a href="#" class="text-white me-3 mr-3"><i class="fab fa-pinterest fa-lg"></i></a>
                    <a href="#" class="text-white me-3 mr-3"><i class="fab fa-youtube fa-lg"></i></a>
                </div>
            </div>
        </div>
        
        <!-- Bottom footer -->
        <div class="row mt-4 pt-4 border-top border-secondary">
            <div class="col-md-6 col-12 text-center text-md-start">
                <p class="mb-2">&copy; 2025 Glossy Cosmetics. All rights reserved.</p>
            </div>
            <div class="col-md-6 col-12 text-center text-md-end">
                <img src="{% static 'images/payment-methods.png' %}" alt="Payment Methods" class="payment-icons" style="max-height: 30px;">
            </div>
        </div>
    </div>
</footer>

templates/includes/main-nav.html
<div class="collapse navbar-collapse" id="main-nav">
    <ul class="navbar-nav w-auto mx-auto">
        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="{% url 'products:skincare' %}" id="skincare-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Skincare
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="skincare-link">
                <a href="{% url 'products:product_category' 'face_cleansers' %}" class="dropdown-item">Face Cleansers</a>
                <a href="{% url 'products:product_category' 'serums' %}" class="dropdown-item">Serums &amp; Treatments</a>
                <a href="{% url 'products:product_category' 'moisturizers' %}" class="dropdown-item">Moisturizers</a>
                <a href="{% url 'products:product_category' 'masks' %}" class="dropdown-item">Masks</a>
                <a href="{% url 'products:product_category' 'eye_care' %}" class="dropdown-item">Eye Care</a>
                <a href="{% url 'products:product_category' 'lip_care' %}" class="dropdown-item">Lip Care</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="{% url 'products:makeup' %}" id="makeup-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Makeup
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="makeup-link">
                <a href="{% url 'products:product_category' 'face' %}" class="dropdown-item">Face</a>
                <a href="{% url 'products:product_category' 'eyes' %}" class="dropdown-item">Eyes</a>
                <a href="{% url 'products:product_category' 'lips' %}" class="dropdown-item">Lips</a>
                <a href="{% url 'products:product_category' 'cheeks' %}" class="dropdown-item">Cheeks</a>
                <a href="{% url 'products:product_category' 'brushes' %}" class="dropdown-item">Brushes &amp; Tools</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="{% url 'products:body_hair' %}" id="body-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Body &amp; Hair
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="body-link">
                <a href="{% url 'products:product_category' 'bath' %}" class="dropdown-item">Bath &amp; Shower</a>
                <a href="{% url 'products:product_category' 'body_moisturizers' %}" class="dropdown-item">Body Moisturizers</a>
                <a href="{% url 'products:product_category' 'hair' %}" class="dropdown-item">Haircare</a>
                <a href="{% url 'products:product_category' 'fragrance' %}" class="dropdown-item">Fragrance</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black" href="{% url 'products:special_offers' %}" id="specials-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Special Offers
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="specials-link">
                <a href="{% url 'products:all_products' %}?sort=price&direction=asc" class="dropdown-item">Price (Low to High)</a>
                <a href="{% url 'products:all_products' %}?sort=price&direction=desc" class="dropdown-item">Price (High to Low)</a>
                <a href="{% url 'products:all_products' %}?sort=rating&direction=desc" class="dropdown-item">Best Rated</a>
                <a href="{% url 'products:all_products' %}?is_featured=True" class="dropdown-item">Featured Products</a>
                <a href="{% url 'products:all_products' %}" class="dropdown-item">All Products</a>
            </div>
        </li>
    </ul>
</div>

templates/includes/mobile-top-header.html
<li class="list-inline-item">
    <a class="text-black nav-link d-block d-lg-none" href="#" id="mobile-search" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="text-center">
            <div><i class="fas fa-search fa-lg"></i></div>
            <p class="my-0">Search</p>
        </div>
    </a>
    <div class="dropdown-menu border-0 w-100 p-3 rounded-0 my-0" aria-labelledby="mobile-search">
        <form class="form" method="GET" action="{% url 'products:all_products' %}">
            <div class="input-group w-100">
                <input class="form-control border border-black rounded-0" type="text" name="q" placeholder="Search our cosmetics">
                <div class="input-group-append">
                    <button class="form-control form-control btn btn-black border border-black rounded-0" type="submit">
                        <span class="icon">
                            <i class="fas fa-search"></i>
                        </span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</li>
<li class="list-inline-item dropdown">
    <a class="text-black nav-link d-block d-lg-none" href="{% url 'accounts:profile' %}" id="user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="text-center">
            <div><i class="fas fa-user fa-lg"></i></div>
            <p class="my-0">My Account</p>
        </div>
    </a>
    <div class="dropdown-menu border-0" aria-labelledby="user-options">
        {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <a href="{% url 'admin:index' %}" class="dropdown-item">Product Management</a>
            {% endif %}
            <a href="{% url 'accounts:profile' %}" class="dropdown-item">My Profile</a>
            <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
        {% else %}
            <a href="{% url 'account_signup' %}" class="dropdown-item">Register</a>
            <a href="{% url 'account_login' %}" class="dropdown-item">Login</a>
        {% endif %}
    </div>
</li>
<li class="list-inline-item">
    <a class="{% if grand_total %}text-primary font-weight-bold{% else %}text-black{% endif %} nav-link d-block d-lg-none" href="{% url 'cart:view_cart' %}">
        <div class="text-center">
            <div><i class="fas fa-shopping-bag fa-lg"></i></div>
            <p class="my-0">
                {% if grand_total %}
                    Rs.{{ grand_total|floatformat:2 }}
                {% else %}
                    Rs.0.00
                {% endif %}
            </p>
        </div>
    </a>
</li>